framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                default_middleware: true
            query.bus: ~

        transports:
            async_fetch: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FETCH)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            async_save: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN_SAVE)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Application\Message\FetchRateMessage: async_fetch
            App\Application\Message\SaveRateMessage: async_save

        # Настройки надежности
        failure_transport: failed