monolog:
    channels: ['deprecation']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!deprecation"]
        # uncomment to get logs in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        stderr:
            type: stream
            path: "php://stderr"
            level: debug
        firephp:
            type: firephp
            level: info
        chromephp:
            type: chromephp
            level: info
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            channels: ["deprecation"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"] 